/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.program5.forms;

import com.program5.entity.CheckingAccount;
import com.program5.entity.SavingAccount;
import java.awt.Dimension;
import javax.swing.JFrame;

/**
 *
 * @author WebleyR
 */
public class ATMPanel extends javax.swing.JFrame {

    CheckingAccount checkingAccount;
    SavingAccount savingsAccount;
    /**
     * Creates new form ATMPanel
     */
    public ATMPanel() {
        initComponents();
       
        // Create a checking account with an initial balance of 500
        var checking = new CheckingAccount(500);
        // Create a savings account with an initial balance of 1000
        var savings = new SavingAccount(1000);
        
        savingsAccount = savings;
        checkingAccount = checking;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        labelOption = new javax.swing.JLabel();
        buttonDeposit = new javax.swing.JButton();
        buttonWithdraw = new javax.swing.JButton();
        buttonTransfer = new javax.swing.JButton();
        buttonTrasactions = new javax.swing.JButton();
        buttonBalance = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainPanel.setName("mainPanel"); // NOI18N

        labelOption.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelOption.setForeground(new java.awt.Color(0, 102, 255));
        labelOption.setText("                   SELECT AN OPTION");
        labelOption.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonDeposit.setBackground(new java.awt.Color(102, 204, 0));
        buttonDeposit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonDeposit.setForeground(new java.awt.Color(255, 255, 255));
        buttonDeposit.setText("DEPOSIT");
        buttonDeposit.setToolTipText("Deporit");
        buttonDeposit.setMaximumSize(new java.awt.Dimension(114, 27));
        buttonDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDepositActionPerformed(evt);
            }
        });

        buttonWithdraw.setBackground(new java.awt.Color(153, 153, 0));
        buttonWithdraw.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonWithdraw.setForeground(new java.awt.Color(255, 255, 255));
        buttonWithdraw.setText("WITHDRAW");
        buttonWithdraw.setToolTipText("WITHDRAW");
        buttonWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWithdrawActionPerformed(evt);
            }
        });

        buttonTransfer.setBackground(new java.awt.Color(153, 204, 0));
        buttonTransfer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonTransfer.setForeground(new java.awt.Color(255, 255, 255));
        buttonTransfer.setText("TRANSFER");
        buttonTransfer.setToolTipText("Deporit");
        buttonTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTransferActionPerformed(evt);
            }
        });

        buttonTrasactions.setBackground(new java.awt.Color(204, 204, 0));
        buttonTrasactions.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonTrasactions.setForeground(new java.awt.Color(255, 255, 255));
        buttonTrasactions.setText("TRANSACTIONS");
        buttonTrasactions.setToolTipText("TRANSACTIONS");
        buttonTrasactions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonTrasactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTrasactionsActionPerformed(evt);
            }
        });

        buttonBalance.setBackground(new java.awt.Color(0, 153, 255));
        buttonBalance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonBalance.setForeground(new java.awt.Color(255, 255, 255));
        buttonBalance.setText("Balances");
        buttonBalance.setToolTipText("TRANSFER");
        buttonBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBalanceActionPerformed(evt);
            }
        });

        buttonExit.setBackground(new java.awt.Color(255, 51, 51));
        buttonExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonExit.setForeground(new java.awt.Color(255, 255, 255));
        buttonExit.setText("EXIT");
        buttonExit.setToolTipText("EXIT");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelOption, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonTrasactions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonWithdraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelOption, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTrasactions, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("ATM Panel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDepositActionPerformed
        var depositForm = new DepositForm(this.savingsAccount, this.checkingAccount);
        depositForm.setVisible(true);
    }//GEN-LAST:event_buttonDepositActionPerformed

    private void buttonWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWithdrawActionPerformed
        var withdrawForm = new WithdrawForm(this.savingsAccount, this.checkingAccount);
        withdrawForm.setVisible(true);      
    }//GEN-LAST:event_buttonWithdrawActionPerformed

    private void buttonTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTransferActionPerformed
        var transferForm = new TransferForm(this.savingsAccount, this.checkingAccount);
        transferForm.setVisible(true); 
    }//GEN-LAST:event_buttonTransferActionPerformed

    private void buttonTrasactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTrasactionsActionPerformed
        var transactionForm = new TransactionForm(this.savingsAccount, this.checkingAccount);
        transactionForm.setVisible(true);
    }//GEN-LAST:event_buttonTrasactionsActionPerformed

    private void buttonBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBalanceActionPerformed
         var balanceForm = new BalanceForm(this.savingsAccount, this.checkingAccount);
        balanceForm.setVisible(true);
    }//GEN-LAST:event_buttonBalanceActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATMPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATMPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATMPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATMPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                var atmPanel = new ATMPanel();
                atmPanel.setTitle("ATM Machine 001");
                atmPanel.setPreferredSize(new Dimension(400, 400));
                atmPanel.setMaximumSize(new Dimension(400,400));
                atmPanel.setResizable(false);
                atmPanel.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                atmPanel.pack();
                atmPanel.setLocationRelativeTo(null);
                atmPanel.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBalance;
    private javax.swing.JButton buttonDeposit;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonTransfer;
    private javax.swing.JButton buttonTrasactions;
    private javax.swing.JButton buttonWithdraw;
    private javax.swing.JLabel labelOption;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
